# Generated by Django 5.1.2 on 2024-11-03 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="auther",
            new_name="author",
        ),
    ]
